### ISSUE TITLE
Psr-4 autoloading standard

### ISSUE THREAD

**Issue by avesgit** [coduo/php-humanizer#114]
Hi i have a problem with your package
`Deprecation Notice: Class Coduo\PHPHumanizer\Tests\CollectionHumanizerTest located in ./vendor/coduo/php-humanizer/tests/Coduo/PHPHumanizer/Tests/CollectionHumanizerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`
Can you update it?

**Comment by norberttech** [comment]
Hey, 
sorry to hear that, unfortunately, I’m a bit busy those days, could you please fix that and open PR? Unless you can wait a couple more days. 
If you decide to contribute I’ll do my best to review it as soon as possible

**Comment by brianwozeniak** [comment]
I believe my pull request will solve the psr-4 autoloading issue for v2.0:

https://github.com/coduo/php-humanizer/pull/115

I also allowed Symfony 5 since Laravel 7 needs that and this caused issues for working there. Composer ends up freezing up in an endless loop trying to figure it out with a message like this:

```
Looking at all rules.
Something's changed, looking at all rules again (pass #623)
```
