### ISSUE TITLE
transChoice is removed as of symfony / translation:5.0

### ISSUE THREAD

**Issue by nickfls** [coduo/php-humanizer#116]
`transChoice` is removed.

[symfony/translation release notes 5.0.0](https://github.com/symfony/translation/blob/b40717fdc075762d03133cad5dab93c6102f6b23/CHANGELOG.md#500)

**Comment by norberttech** [comment]
Right, thats very inconvenient, meaning that current ^5.0 version support does not work at all, I think I will just reduce the supported translator version for humanizer branch to ^4.0 and release new version of humanizer, 4.0 that will start support from symfony components ^5.0 and php 7.3. 
Since this is dependency of php-matcher I will make sure that matcher can work with humanizer version ^3.0 and ^4.0 at the same time since ^4.0 of humanizer will not change humanizer api but only drop support for older versions of symfony. 

I think that's the only solution because even the TranslatorInterface on which currently humanizer relay was moved to `symfony/translation-contracts`

**Comment by norberttech** [comment]
I just pushed new branch 4.x which resolves that issue
