### ISSUE TITLE
Is Symfony really required?

### ISSUE THREAD

**Issue by 7rust** [coduo/php-humanizer#32]
Composer said that Symfony is required for php-humanizer. Is that correct? 

IMO: That would be a bit too much just for this little framework :open_mouth:

**Comment by Divi** [comment]
This is not Symfony, but only its components. It won't install the whole framework, don't worry.

**Comment by 7rust** [comment]
But its definitly required?

**Comment by Divi** [comment]
Sure, it allows this lib to use a Yaml parser and replace string with a translation.  
Without these components, the author(s) should have to reinvent the wheel (or use another lib, which it's the same).

**Comment by norzechowicz** [comment]
symfony/intl, symfony/translation and symfony/yaml are required in order to not reinvent the wheel just like @Divi said. I guess we can remove symfony/config, I gonna check that later.

**Comment by norzechowicz** [comment]
Ahh we can't remove symfony/config also because symfony/translation use it but its not defined as a dependnecy. It was fixed in [Symfony 2.7](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/Loader/YamlFileLoader.php#L68) by adding class_exists function but if we change that we gonna create BC Break so for now its gonna stay as is.
